FROM node:20

WORKDIR /usr/src/backend

COPY package.json yarn.lock ./

RUN yarn install
COPY prisma ./prisma
COPY src ./src

RUN yarn add @prisma/client
RUN yarn prisma generate

CMD ["sh", "-c", "yarn start:dev"]
