FROM node:20-alpine AS builder

WORKDIR /usr/src/backend

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

COPY . .
RUN yarn build

FROM node:20-alpine AS production

WORKDIR /usr/src/backend

COPY --from=builder /usr/src/backend/dist ./dist
COPY --from=builder /usr/src/backend/package.json ./package.json
COPY --from=builder /usr/src/backend/yarn.lock ./yarn.lock

RUN yarn install --production --frozen-lockfile

EXPOSE 3000
CMD ["node", "dist/main"]
