import { applyDecorators, HttpStatus } from '@nestjs/common';
import {
  ApiOperation,
  ApiResponse,
  ApiParam,
  ApiBody,
  ApiBadRequestResponse,
  ApiNotFoundResponse,
  ApiConflictResponse,
} from '@nestjs/swagger';
import { CreateEmployeeDto } from './dto/create-employee.dto';
import { UpdateEmployeeDto } from './dto/update-employee.dto';

const id = '123e4567-e89b-12d3-a456-426614174000'
const data_resposta = '2024-12-01T10:30:00.000Z'
function ApiUuidParam(name: string = 'id') {
  return ApiParam({
    name,
    description: 'Unique employee ID (UUID format)',
    example: id,
    type: 'string',
    format: 'uuid',
  });
}

function ApiEmployeeNotFound() {
  return ApiNotFoundResponse({
    description: 'Employee not found',
    schema: {
      example: {
        statusCode: 404,
        message: 'Employee not found',
        error: 'Not Found',
      },
    },
  });
}

function ApiInvalidUuid() {
  return ApiBadRequestResponse({
    description: 'Invalid ID (not a valid UUID)',
    schema: {
      example: {
        statusCode: 400,
        message: 'Validation failed (uuid is expected)',
        error: 'Bad Request',
      },
    },
  });
}

function ApiEmailConflict() {
  return ApiConflictResponse({
    description: 'Email already registered',
    schema: {
      example: {
        statusCode: 409,
        message: 'There is already an employee with this email registered.',
        error: 'Conflict',
      },
    },
  });
}

const dtoComplete = {
    nome: 'Anya Forger',
    email: 'anya.forger@email.com',
    email_corporativo: 'anya.forger@empresa.com',
    area: 'tecnologia',
    cargo: 'gerente',
    funcao: 'gestor',
    localidade: 'Fortaleza',
    tempo_de_empresa: 'mais de 5 anos',
    genero: 'feminino',
    geracao: 'geração z',
    n0_empresa: 'Empresa a',
    n1_diretoria: 'diretoria a',
    n2_gerencia: 'gerência a1',
    n3_coordenacao: 'coordenação a11',
    n4_area: 'área a111',
    interesse_no_cargo: 4,
    comentarios_interesse: 'I really like my current position',
    contribuicao: 5,
    comentarios_contribuicao: 'Estou motivado a contribuir...',
    aprendizado_desenvolvimento: 7,
    comentarios_aprendizado: 'Gostaria de participar de projetos...',
    feedback: 3,
    comentarios_feedback: 'Gostaria de receber mais feedbacks',
    interacao_gestor: 7,
    comentarios_interacao: 'Meu gestor é acessível',
    clareza_carreira: 3,
    comentarios_carreira: 'Gostaria de ter mais clareza',
    expectativa_permanencia: 7,
    comentarios_permanencia: 'Me sinto motivado a permanecer na empresa.',
    enps: 9,
    enps_aberto: 'É uma boa empresa pra se trabalhar!'
  
}

export function ApiCreateEmployee() {
  return applyDecorators(
    ApiOperation({
      summary: 'Create new employee',
      description:
        'Creates a new employee record in the system. ' +
        'Evaluation data is optional and can be provided later. ' +
        'The data_resposta is automatically generated by the system.',
    }),

    ApiBody({
      type: CreateEmployeeDto,
      description: 'Employee data to be created',
      
    }),

    ApiResponse({
      status: HttpStatus.CREATED,
      description: 'Employee created successfully',
      schema: {
        example: { id, ...dtoComplete, data_resposta },
      },
    }),

    ApiEmailConflict(),

    ApiBadRequestResponse({
      description: 'Invalid data',
      schema: {
        example: {
          statusCode: 400,
          message: [
            'Invalid email',
            'interesse_no_cargo must be at most 7',
            'enps must be between 0 and 10',
          ],
          error: 'Bad Request',
        },
      },
    }),
  );
}

export function ApiFindAllEmployees() {
  return applyDecorators(
    ApiOperation({
      summary: 'List all employees',
      description:
        'Returns a list of all employees registered in the system, ' +
        'sorted by most recent response date.',
    }),
    ApiResponse({
      status: HttpStatus.OK,
      description: 'List of employees returned successfully',
      schema: {
        example: [
          { id, ...dtoComplete, data_resposta },{ id, ...dtoComplete, data_resposta }
        ],
      },
    }),
  );
}

export function ApiFindOneEmployee() {
  return applyDecorators(
    ApiOperation({
      summary: 'Find employee by ID',
      description:
        'Returns complete data of a specific employee by their unique UUID.',
    }),

    ApiUuidParam(),
    ApiResponse({
      status: HttpStatus.OK,
      description: 'Employee found successfully',
      schema: {
        example: { id, ...dtoComplete, data_resposta },
      },
    }),

    ApiEmployeeNotFound(),
    ApiInvalidUuid(),
  );
}

export function ApiUpdateEmployee() {
  return applyDecorators(
    ApiOperation({
      summary: 'Update employee basic data',
      description:
        'Updates ONLY basic employee data (name, email, position, area, etc). ' +
        'Evaluation/survey fields CANNOT be changed after submission. ' +
        'The data_resposta field also cannot be modified.',
    }),

    ApiUuidParam(),
    ApiBody({
      type: UpdateEmployeeDto,
      description: 'Employee basic data to be updated',
      examples: {
        'update-contact': {
          summary: 'Update tempo_de_empresa data',
          value: {
            tempo_de_empresa: 'mais de 6 anos',
          },
        },
        'update-location': {
          summary: 'Update location',
          value: {
            localidade: 'São Paulo',
          },
        },
      },
    }),
    ApiResponse({
      status: HttpStatus.OK,
      description: 'Employee updated successfully',
      schema: {
        example: {
          id,
          ...dtoComplete,
          localidade: 'São Paulo',
          tempo_de_empresa: 'mais de 6 anos',
          data_resposta,
        }
      },
    }),

    ApiEmployeeNotFound(),
    ApiEmailConflict(),

    ApiBadRequestResponse({
      description: 'Attempt to change protected fields or invalid data',
      schema: {
        example: {
          statusCode: 400,
          message: 'The enps field cannot be changed after the survey has been submitted',
          error: 'Bad Request',
        },
      },
    }),

  );
}

export function ApiDeleteEmployee() {
  return applyDecorators(
    ApiOperation({
      summary: 'Remove employee',
      description:
        'Permanently removes an employee from the system by their unique ID. ' +
        'This action cannot be undone.',
    }),
    ApiUuidParam(),
    ApiResponse({
      status: HttpStatus.OK,
      description: 'Employee removed successfully',
      schema: {
        example: {id, ...dtoComplete, data_resposta}
      },
    }),
    ApiEmployeeNotFound(),
    ApiInvalidUuid(),
  );
}